### ISSUE TITLE
Multi file upload

### ISSUE THREAD

**Issue by thiagoalmeidasa** [jim-at-jibba/micropython.nvim#1]
Hey, thank you so much for your project.
Being able to easily code and connect to my Raspberry Pico from my existing Nvim setup made my day. For real. Thanks.

Now I'm trying to upload multiple files containing some libs along with the `main.py`. Would it be possible to add an optional argument to the `:MPUpload` command to define a filename for the upload?

Thanks again.

**Comment by jim-at-jibba** [comment]
Hey buddy,

Yeah that kind of thing is next on my list. 

My idea is that there would be an `MPUploadAll` command that would upload the whole project. 

Does that sound like what you are after?

**Comment by jim-at-jibba** [comment]
@thiagoalmeidasa I have started working on this. What do you think is the best approach to handling files we don't want to upload? I am currently excluding the `.git` folder and `.ampy` file. Should the `MPUpladAll` command accept a list of ignored files and folders?

**Comment by thiagoalmeidasa** [comment]
That's an awesome idea. `MPUploadAll`  with an `ignored` arg receiving a list of glob patterns to match.
It sounds like you found a good path.
Thanks again

**Comment by jim-at-jibba** [comment]
This has been completed in #2 

@thiagoalmeidasa have a play and let me know what you think
