### ISSUE TITLE
Cannot set port with :MPSetPort, :MPRepl drops to rshell

### ISSUE THREAD

**Issue by viscount-monty** [jim-at-jibba/micropython.nvim#6]
Thanks for making this plugin, it was exactly what I was looking for! A couple minor bugs:

Firstly I am running 
- Neovim `NVIM v0.11.0-dev-1106+gf7e32fb6e6`
- Linux Mint 22 Cinnamon
- Raspberry Pi Pico `MicroPython v1.24.0 on 2024-10-25; Raspberry Pi Pico W with RP2040`

When I run the Neovim command `:MPSetPort` the following is displayed:
![image](https://github.com/user-attachments/assets/ec096c67-835b-49fb-ba09-90a4be6ea161)
- There appears to be no ports listed to choose from
- When I type the correct port (`/dev/ttyACM0`) and press enter, the window disappears and a `No selection made` message appears in the command window

When I run the bash command `rshell -l` I get the following output:
```
Serial Device: /dev/ttyS0
[ ... ]
Serial Device: /dev/ttyS31
USB Serial Device 2e8a:0005 with vendor 'MicroPython' serial 'e6614c311b712739' intf 'Board CDC' found @/dev/ttyACM0 *
```

The `.ampy` file created by `:MPInit` has a default port setting of `dev/ttyUSB0`. If I manually change this to `/dev/ttyACM0` I am able to run the other commands successfully.

Sub-issue: `:MPRepl` drops me at an `rshell` prompt instead, but issuing the `repl` command gets to the REPL. Perhaps line 9 in `/lua/micropython_nvim/repl.lua`, which is currently:
```lua
local repl_assembled_command = string.format('rshell -p %s', _G['AMPY_PORT'])
```
Should be
```lua
local repl_assembled_command = string.format('rshell -p %s repl', _G['AMPY_PORT'])
```

And another function could be made for `rshell`?

**Comment by jim-at-jibba** [comment]
Hey buddy, 

Thanks for letting me know about these. I have fixed them both. I have made the the port filtering more flexible by filtering by
the following:
 
```lua
  local patterns = {
    '/dev/ttyUSB*', -- USB-to-Serial adapters
    '/dev/ttyACM*', -- Arduino and similar CDC devices
    '/dev/ttyS*', -- Hardware serial ports
    '/dev/tty.usbmodem*',
  }
```

Let me know if you have any other issues

**Comment by viscount-monty** [comment]
Perfect, thanks!
